### ISSUE TITLE
Npc respawn

### ISSUE THREAD

**Issue by ZimL12** [JKAnderson/DSR-Gadget#17]
For some reason i only can make npcs non hostile but after they die i cant spawn them back and i only hear the msaying their last sentence before dying over and over again. How can i fix it?

**Comment by anthops** [comment]
Did you manage to figure this one out? I'm in the same boat

**Comment by anthops** [comment]
Nvm turns out there were a few more event flags needed. To fully revive the fair lady and eingyi, as well as make the bonfire work again, you'll have to:

- enable 1270
- disable 1272
- disable 11400521
- enable 1280
- disable 1284
- disable 1287
- disable 11400522
- disable 11400800
- disable 11400501
- disable 140
